title: Ihboras Data Science Portfolio
author: 
  name: David Hunt
  email: ihboras3@hotmail.com
#logo:
description: Welcome to my Data Science Portfolio! Please have a look around
#show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
